-- customer table relation query

-- SQL query to retrieve all the customer information along with the total number of orders placed by each customer
SELECT
    c.customer_id,
    c.name,
    c.email,
    c.location,
    COUNT(o.order_id) AS total_orders
FROM
    customers c
LEFT JOIN
    Orders o ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id, c.name, c.email, c.location
ORDER BY
    total_orders DESC;




--  SQL query to retrieve the product name, quantity, and total amount for each order item


SELECT
    p.name AS product_name,
    oi.quantity,
    oi.quantity * oi.unit_price AS total_amount
FROM
    Order_Items oi
JOIN
    Products p ON oi.product_id = p.product_id
ORDER BY
    oi.order_id ASC;


-- SQL query to retrieve the total revenue generated by each product category

SELECT
p.name AS product_name,
    c.name AS category_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM
    Categories c
JOIN
    Products p ON c.category_id = p.category_id
JOIN
    Order_Items oi ON p.product_id = oi.product_id
GROUP BY
    c.name
ORDER BY
    total_revenue DESC;


-- SQL query to retrieve the top 5 customers who have made the highest total purchase amount


SELECT
    c.name AS customer_name,
    SUM(o.total_amount) AS total_purchase_amount
FROM
    Customers c
JOIN
    Orders o ON c.customer_id = o.customer_id
GROUP BY
    c.name
ORDER BY
    total_purchase_amount DESC
LIMIT 5;
